/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "PWM_Motor.h"
#include "Reset_pin_aliases.h"
#include "Reset_pin.h"
#include "Aumentar_aliases.h"
#include "Aumentar.h"
#include "LED_aliases.h"
#include "LED.h"
#include "Reset_PWM_aliases.h"
#include "Reset_PWM.h"
#include "timer_clock.h"
#include "Disminuir_aliases.h"
#include "Disminuir.h"
#include "isr_Aumentar.h"
#include "isr_Disminuir.h"
#include "MOTOR_aliases.h"
#include "MOTOR.h"
#include "QuadDec.h"
#include "encoder_A_aliases.h"
#include "encoder_A.h"
#include "encoder_B_aliases.h"
#include "encoder_B.h"
#include "isr_Ts.h"
#include "Timer.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "QuadDec_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

